name: Publish container images
on:
  workflow_dispatch:
env:
  REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
  OWNER: idemsinternational
jobs:
  publish:
    strategy:
      matrix:
        image:
          - enketo
          - nginx
          - secrets
          - service
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY -u $ --password-stdin
      - name: Publish
        env:
          IMAGE_TAG: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ matrix.image }}:latest
        run: |
          docker build --tag $IMAGE_TAG -f ${{ matrix.image }}.dockerfile .
          docker push $IMAGE_TAG
